### ISSUE TITLE
Same ClusterID/SpeakerID for the incoming files

### ISSUE THREAD

**Issue by vinayentc** [BUTSpeechFIT/VBx#11]
Hello Federico,

Can you please suggest if we can in any way keep the clusterID/speakerID same for the incoming short clips from the same audio.  Actually i am trying to implement it for the streaming mode, wherein we get the short chunks of audio/of people speaking on the microphone. However for every new chunk the speaker id is new even though the speakers are actually the same. e.g. If only 1 speaker is actually speaking then every 10 seconds new chunk will be received and every time the cluster id or the speaker id generated will be different giving the sense that multiple speakers are speaking.

I tried one approach to keep adding the embeddings to the existing ark file in the predict.py as below, however the clustering process will be very slow as the .ark file grows -

Can you please suggest any way in which this can be achieved. Kindly let me know for any further information required. Thanks.!!

Part 1, At the start -

    ark_dict_existing = {}
    ark_dict_exist = False
    if os.path.isfile(out_ark_file):
        ark_dict_exist = True
        for key, numpy_array in kaldi_io.read_vec_flt_ark(out_ark_file):
            ark_dict_existing[key] = numpy_array

Part 2 , At the end - 

    if ark_dict_exist:
        ark_dict_temp = {}
        for key, numpy_array in kaldi_io.read_vec_flt_ark(out_ark_file):
            ark_dict_temp[key] = numpy_array

        ark_dict_new = dict(ark_dict_existing, **ark_dict_temp)

        with open(out_ark_file, 'wb') as f:
            for key, vec in ark_dict_new.items():
                kaldi_io.write_vec_flt(f, vec, key=key)

Regards,
Vinay

**Comment by fnlandini** [comment]
Hello Vinay,

I think in any case with this framework you will have to compare the embeddings from the new segment with those already clustered. One possibility is to do diarization on each 10s chunk separately and then compare the embeddings of the speakers after diarization on the short chunks to know who corresponds with whom. However, I think it is best to do this by simply running VBx on the whole sequence up to now. The most time consuming part of VBx is actually the AHC initialization (especially for very long recordings) so you could skip that step.
One way of doing this is to take advantage of the previous clustering output because you already have labels for the speakers. Then, you can assign random labels only in the new 10s and run only the VB iterations (no AHC). That should be fast enough.

I understand that you are not recalculating the x-vectors for the whole sequence again and again. But I do not see why you need to add the embeddings to an existing ark file. You should be computing separate files and only loading the embeddings. This is definitely what takes most of the time in the whole pipeline.

Let me know if you still have any question.

**Comment by vinayentc** [comment]
Hello Federico,

Below response - 

1. I think it is best to do this by simply running VBx on the whole sequence up to now -> I understand that we can run predict.py on the incoming chunks and save the separate .seg and .ark files as per the input chunk name. But running the VBx (vbhmm.py) on the separate .ark and .seg files we will still generate new cluster/speaker ids everytime.

2. The most time consuming part of VBx is actually the AHC initialization (especially for very long recordings) so you could skip that step -> To skip AHC initialization do we need to set init='VB' and not init = 'VB+AHC'. Is the understanding correct. If we set init='VB' only then we get the error for _labels1st_ as it is not assigned any value

            if args.init.endswith('VB'):
                # Smooth the hard labels obtained from AHC to soft assignments
                # of x-vectors to speakers
                qinit = np.zeros((len(labels1st), np.max(labels1st) + 1))

3. But I do not see why you need to add the embeddings to an existing ark file. - 
This excerpt is from vbhmm.py file,  As mentioned here in the help i attempted to add to single ark file -

    parser.add_argument('--xvec-ark-file', required=True, type=str,
                        help='Kaldi ark file with x-vectors from one or more input recordings. '
                             'Attention: all x-vectors from one recording must be in one ark file')

4. You should be computing separate files and only loading the embeddings -> Can you please suggest how this can be achieved.

Thanks,
Vinay

**Comment by fnlandini** [comment]
Hi,
All of the possibilities I suggested require some changes in the code. You are trying to use this code (which does offline diarization) to do online diarization so the recipe as it is will not work and the changes might require some work.

1. I mean loading all the ark and seg files separately but put them together so that you run VBx over the whole sequence up to the current time. In this case, you will have to be careful with the segmentation times as you will need to make them fit as if they were timings from a single recording (which actually they are).

2. In order to skip the step, you still have to define labels1st because that contains the initialization. You can assign random speaker labels to it and the VB updates will modify them to produce something sensible. Bear in mind that the amount of different speakers will define how many speakers you can find in the recording.

3. With the current code, the help asks all segments from a recording to be together in order to create a dictionary that can be processed afterwards. You will need to make changes to load different arks into a single dictionary if you want to keep that part of the code.

4. I am not sure exactly how is your pipeline as you are working on a streaming fashion. My guess is that you read one 10s chunk at a time every 10 seconds. What I would do is to generate x-vectors for that chunk and save them but somehow keep record of what global time corresponds to that chunk (the first chunk will go from 0 to 10, the second from 10 to 20 and so on). Then, you load the xvectors of all the chunks up to now, put them one after the other in order, while adjusting the segmentation so that they correspond to the total file now, and run VBx with the whole set of x-vectors up to the current time.
If VBx runs fast enough with this approach, you don't need to worry about skipping AHC. If not, I would save the VBx output so far so that in the next step I use it for initialization (put it in labels1st) and assign random labels to the "new" x-vectors. 
I might be overlooking some things as I do not have much experience with online diarization.

Feel free to write me an email to landini@fit.vutbr.cz to discuss this.
If I want to see your suggestion as an issue for the repo, I would say that right now we are not planning on modifying it to be directly usable for online diarization.

**Comment by MireiaDS** [comment]
Hello Vinay, let me share a few more thoughts in this line.

To run the VBx while adding small chunks at a time, you could reuse the previous output labels, like Fede suggested. 
Keep in mind that the only thing you need for building the speaker models are the statistics collected from the assignment of frames (x-vectors) to the speakers from the input audio. To be precise, if you look to equations (16) and (17) (https://arxiv.org/abs/2012.14952) each equation has only one summation over time, if you fix the past diarization output this summation is also fixed and you do not need to repeat it in future runs. You could sum and store these using the diarization output from the last run and directly use them to initialize the speaker models. Of course if you fix the past, future samples do not affect the inference of the past audio.
Next, you need to consider how to initialize the labels for the new chunk. It is important to remember that the VBx cannot converge to more speakers than what it is initialized with so if you do not provide new labels it won’t find new speakers. You could attempt simply using one/two/a_few new random labels (depending on how many new speakers you could expect in the new chunk) for the initialization of this new chunk. Nevertheless, although I have not really tried it in this specific scenario, I am not sure if this would behave well. A good initialization tends to be key for having the VBx have a good performance, so giving reasonable initial labels to the new chunk might be better. You could try to perform some pre-clustering of the new x-vectors to the existing speakers (or assign them to a new speaker) with AHC with a pre-fixed tuned threshold, or some other heuristic in this line, and then run VBx. 
This VBx run would need to collect the statistics for the new segment, add them to the pre-stored ones, and proceed with the updates.

I am omitting several details and there are several variants of this that can be considered but I think that this would a reasonable direction to attempt for online diarization. Of course, it requires certain understanding of the code to be able to make modifications.

**Comment by vinayentc** [comment]
Hello Federico, Hello Mireia,

Thanks a lot for the response.  I am able to make the changes to the code as suggested and able to achieve the results, however it seem some further updates might be required. Below steps done as suggested to achieve the expected results - 
1. Merge the incoming chunk of wav files, so that there 1 single consolidated audio file
2. Run the energy VAD on the combined audio file. This *.lab file now keeps the record of what global time
3. Run predict.py to get the embeddings by using this combined audio file and combined *.lab file, but restrict only for the new chunk and not for complete audio file
4. Merge the embeddings and segments of the new chunk to one global combined *.ark and *.seg file 
5. Run vbhmm.py to get the new/random clusters for the new chunk and then run VBx on them as per the existing code
6. Merge the VBx generated clusters to the global labels/clusters *.txt file
7. Initialize the labels saved in global/combined cluster/labels *.txt file and then run VBx on the same. Then update the global/combined cluster/labels *.txt file after VBx run (this was crucial step, 1st missed and therefore could not get the desired results, however the same could fix)

The code works very well for long period of time of about 30 min to 60 min and handles the diarization. However randomly  below error is recived -

File - “VB_diarization.py", line 109, in VB_diarization
 VtiEFs = gamma.T.dot(VtiEF)                           # eq. (35) except for \Lambda_s^{-1} for all 's'
ValueError: shapes (5,3654) and (3656,128) not aligned: 3654 (dim 1) != 3656 (dim 0)
CRITICAL - shapes (5,3654) and (3656,128) not aligned: 3654 (dim 1) != 3656 (dim 0)

Can you please point to any reason where it can  checked. The .ark and .seg files have equal number of entries.

Thanks,
Vinay

**Comment by fnlandini** [comment]
Hi Vinay,

I am glad to see you have put together a solution. As for the error, I cannot exactly know because I do not know the exact modifications to the code you did but I have a possible reason.
Notice that the line that fails is trying to multiply gamma and VtiEF and fails because the amount of frames differ by 2. VtiEF has an amount of frames equal to those in the input X (see https://github.com/BUTSpeechFIT/VBx/blob/d0b2b77b503d0c149c901e10c0bfffbdc5c8a136/VBx/VB_diarization.py#L97). gamma's number of frames depends on the content of labels1st from vbhmm.py (see https://github.com/BUTSpeechFIT/VBx/blob/d0b2b77b503d0c149c901e10c0bfffbdc5c8a136/VBx/vbhmm.py#L128). From your explanation, I understand that you are loading the initialization labels for VBx from a txt file so it might be possible that in some case the amount of labels you are saving/loading is slightly shorter than it should be. I would try to debug in this direction to understand where the error comes form.

Best,
Federico

**Comment by vinayentc** [comment]
Hello Federico, Thanks for the response. With the provided direction , i was able to handle the issue.  There was a mismatch between the count of embeddings in the combined *.ark file and the combine *.txt (total clusters/speakers) count. I am not able to find how/why this mismatch is happening as it is random, however currently i have handled this exception and continue with the streaming diarization process.

Thanks,
Vinay Raut
