### ISSUE TITLE
telephone codec

### ISSUE THREAD

**Issue by wbgxx333** [BUTSpeechFIT/VBx#18]
thank you for this wonderful contribution.

i read the paper,"https://arxiv.org/pdf/2012.14952.pdf"*(F. Landini, J. Profant, M. Diez, L. Burget: Bayesian HMM clustering of x-vector sequences (VBx) in speaker diarization: theory, implementation and analysis on standard tasks).

the 8kHz:Any wide-band data used were
downsampled to 8 kHz and passed through a telephone codec.
i want to know what is the telephone codec.maybe use the g711 to encode and decode?

thank you very much.

**Comment by fnlandini** [comment]
Hi,
Unfortunately, I do not know the details about the codecs as it was a colleague of mine who trained the extractor. He will reply in the corresponding repository where you opened the same issue: https://github.com/phonexiaresearch/VBx-training-recipe/issues/5
He should be able to reply soon there. Meanwhile, I will close this issue here.

**Comment by wbgxx333** [comment]
thank you very much. and i will wait
