### ISSUE TITLE
Division by zero in AHC

### ISSUE THREAD

**Issue by Jamiroquai88** [BUTSpeechFIT/VBx#21]
Hey, I wanted to ask about a problem in AHC - division by zero.
```
diarization_lib.py:30: RuntimeWarning: divide by zero encountered in true_divide
  threshold = -0.5 * (np.log(weights ** 2 / var) - means ** 2 / var).dot([1, -1]) / (means / var).dot([1, -1])
diarization_lib.py:30: RuntimeWarning: invalid value encountered in subtract
  threshold = -0.5 * (np.log(weights ** 2 / var) - means ** 2 / var).dot([1, -1]) / (means / var).dot([1, -1])
Traceback (most recent call last):
  File "vbhmm.py", line 130, in <module>
    labels1st = AHC(scr_mx, thr + args.threshold)
  File "diarization_lib.py", line 53, in AHC
    dist[:, mi] = dist[mi, :] = (dist[mi, :] * len(clsts[mi]) + dist[mj, :] * len(clsts[mj])) / (
TypeError: object of type 'NoneType' has no len()
```
For now, I solved it like this before division by `var`:
```python
if abs(var) < var_eps:  # avoid division by zero
    break
```

**Comment by Jamiroquai88** [comment]
A little more info, I believe the problem starts in `twoGMMcalib_lin` with the `var` variable ... I realized it might not be clear from the message above

**Comment by fnlandini** [comment]
Hi,

I remember having seen the warning about division by zero but it does not stop the execution. From the error (`object of type 'NoneType' has no len()`) it seems to me that the problem is related to `clsts` which is defined by `cos_similarity`. 
I wonder if the cosine similarity is the same for all pairs or there is a single xvector or something in that direction. Did you check if `scr_mx` has something strange? Or is it similar to other (successful) runs?

**Comment by DTDwind** [comment]
This issue will happen on evaluate IS1009a, IS1009b.
METHOD=AHC
It will stop grid engine process, and didn't generate the rttm.

**Comment by Jamiroquai88** [comment]
I believe that once those warnings are shown, in some cases it crashes in the next steps. I was not able to replicate these warnings on my Mac, so it has probably something with the architecture you are running on. Closing, for now, looks like avoiding the division by zero in `var` works.
