### ISSUE TITLE
Low Accuracy for 15 sec or 30 sec audio clips

### ISSUE THREAD

**Issue by vinayentc** [BUTSpeechFIT/VBx#6]
Hello,

I have a set of 15 or 30 sec clips, however the model provides less accurate results for these short clips. If the clips are merged into larger audio file then the results improve. I tried changing some of the input parameters but to no success. 

Can you please suggest if any of the settings can be changed for the 15 sec or 30 sec audio clips so that the accuracy can be improved for them as well.

Thanks a lot,
Vinay

**Comment by fnlandini** [comment]
Hello Vinay,
We have not explored so short segments with VBx. Usually the recordings we use for diarization are of at least a few minutes long.
I am not sure if you are trying to use the tool for speaker verification (where such short segments are more common) or diarization given the question you asked previously.
If for diarization, I guess your recordings will have 1 or 2 speakers only (or similar, since they are so short). Then, I would recommend you to use a configuration similar to the recipe for CALLHOME because those recordings usually have 2 or 3 speakers. The most relevant hyperparameter for this is FB and I would set it to some large value (in CALLHOME we used 17 so you can try some values around that). Note that there is some interplay with other hyperparameters and you might need to play a bit with them. The most relevant is FA. Figure 4 of our previous [paper](https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=8910412) shows how FA and FB relate. Those results are not with VBx so the specific numbers will not be the same but the relationship will be quite similar.
Let us know if you have other questions. We will be interested in seeing your results if you want to share them.

Thanks,
Federico

**Comment by vinayentc** [comment]
Hello Federico, 

Thanks for the response. In this case I am working with the unsupervised diarization problem (not for speaker verification).

As suggested, I tried the settings from recipe for CALLHOME. Also as tried changing the hyperparameters like one's below -
threshold = -0.015
lda_dim = 128 
Fa = 1
Fb =  17.18
loopP = 0.99
target_energy = 1.0
init_smoothing = 7.0

However this worked well for few segments but could not generalize well. 

I further tried to change the segment length and segment jump as well with no much advantage.

- Can you please mention if "target_energy" parameter is used in the code as I don't see that parameter being used anywhere further in the code.
- Also URL - " http://www.fit.vutbr.cz/∼mireia/DER_plots.pdf " from the paper is not accessible required to refer the various parameters tried.
- One point could not understand, if there are 10 clips, why it works well for 4-5 clips and not for the others when the same 2 speaker are speaking throughout.
- Do you see any further/different approach can be used in this case.

Thanks,
Vinay

**Comment by fnlandini** [comment]
Hi Vinay,
Thank you for pointing out that target_energy is not used. I have just removed it. It was part of our first release of the code which used the parameter when doing AHC using PLDA (rather than cosine).
Also thanks for mentioning the link. The problem there is that the latex character for ~ is wrong. This should work: http://www.fit.vutbr.cz/~mireia/DER_plots.pdf

As for why the model works in some clips and not in others is hard to say without further information. Also, not working well could mean over-cluster or under-cluster (assuming good VAD) and the amount of speakers in each clip could matter. But it could also be the quality of the recordings (noise). It is really hard to say without context.
I see you used Fb=17.18 but when I thought of larger values I should have exemplified 18, 19, 20, ...

Federico

**Comment by vinayentc** [comment]
Currently receiving better accuracy for the short clips with the below configuration -

threshold = -0.015
lda_dim = 128
Fa = 1
Fb = 18
loopP = 0.99
init_smoothing = 5.0

Thanks a lot for the help and support. Will further test and report any changes.

Regards,
Vinay Raut
